value = {'PushEvent'              
,
'CreateEvent'                      
,
'DeleteEvent'                        
,
'PullRequestEvent'                  
,
'IssuesEvent'                        
,
'WatchEvent'                        
,
'IssueCommentEvent'                  
,
'PullRequestReviewCommentEvent'               
,
'PullRequestReviewEvent'            
,
'ForkEvent'                          
,
'ReleaseEvent'                        
,
'MemberEvent'                        
,
'PublicEvent'                          
,
'GollumEvent'                          
,
'DiscussionEvent'                      

,'CommitCommentEvent'}